#ifndef SMARTBOOK_COMMON_FORMS_FORMDATASERIALIZER_H
#define SMARTBOOK_COMMON_FORMS_FORMDATASERIALIZER_H

#include <QString>
#include <QWidget>
#include <QJsonValue>

namespace smartbook {
namespace common {
namespace forms {

/**
 * @brief Serializer for form data to/from JSON
 * 
 * FormDataSerializer extracts form data from Qt Widgets and converts it to JSON,
 * and vice versa. It handles all supported form field types and works with form
 * widgets generated by FormSchemaParser.
 * 
 * @section Serialization
 * 
 * **Widget to JSON:**
 * - Iterates through QFormLayout rows
 * - Extracts values from widgets using `objectName` as field name
 * - Converts widget values to JSON values
 * - Returns compact JSON string
 * 
 * **JSON to Widget:**
 * - Parses JSON data
 * - Finds widgets by `objectName` (field name)
 * - Sets widget values from JSON values
 * - Handles type conversions automatically
 * 
 * @section Supported Widget Types
 * 
 * **Text Input (QLineEdit):**
 * - Serializes: `text()` → JSON string
 * - Deserializes: JSON string → `setText()`
 * 
 * **Textarea (QTextEdit):**
 * - Serializes: `toPlainText()` → JSON string
 * - Deserializes: JSON string → `setPlainText()`
 * 
 * **Select (QComboBox):**
 * - Serializes: `currentText()` → JSON string
 * - Deserializes: JSON string → `setCurrentText()`
 * 
 * **Checkbox (QCheckBox):**
 * - Serializes: `isChecked()` → JSON boolean
 * - Deserializes: JSON boolean → `setChecked()`
 * 
 * **Radio Buttons (QRadioButton + QButtonGroup):**
 * - Serializes: Selected button text → JSON string
 * - Deserializes: JSON string → Select matching button
 * 
 * **Number (QSpinBox, QDoubleSpinBox):**
 * - Serializes: `value()` → JSON number
 * - Deserializes: JSON number → `setValue()`
 * 
 * **Date (QDateEdit):**
 * - Serializes: `date().toString(Qt::ISODate)` → JSON string
 * - Deserializes: JSON string → `setDate(QDate::fromString(..., Qt::ISODate))`
 * 
 * @section Widget Identification
 * 
 * **Critical Requirement:**
 * - All form widgets MUST have their `objectName` set to the field name
 * - FormSchemaParser automatically sets `objectName` when creating widgets
 * - Serializer uses `objectName` to match JSON fields to widgets
 * 
 * @section Usage
 * 
 * @code
 * FormDataSerializer serializer;
 * 
 * // Serialize form data
 * QString jsonData = serializer.serializeFormData(formWidget);
 * // jsonData: {"name": "John", "email": "john@example.com"}
 * 
 * // Deserialize form data
 * bool success = serializer.loadFormData(formWidget, jsonData);
 * if (!success) {
 *     QString error = serializer.lastError();
 *     // Handle error
 * }
 * @endcode
 * 
 * @section Error Handling
 * 
 * **Serialization Errors:**
 * - Returns empty string if form widget is null
 * - Returns empty string if form widget doesn't have QFormLayout
 * - Widgets without `objectName` are skipped (no error)
 * 
 * **Deserialization Errors:**
 * - Returns false if form widget is null
 * - Returns false if JSON is invalid
 * - Returns false if form widget doesn't have QFormLayout
 * - Widgets not found in JSON are skipped (no error)
 * - Type conversion failures are logged but don't stop deserialization
 * 
 * @note This class is stateless (except for lastError). Multiple instances
 * can be used concurrently without issues.
 * 
 * @see FormSchemaParser
 * @see FormWidgetGenerator
 * @see FormValidator
 * @see FormEmbeddedWidget
 * @see qt-widgets-forms-guide.adoc
 */
class FormDataSerializer {
public:
    FormDataSerializer();
    ~FormDataSerializer();
    
    /**
     * @brief Serialize form data from widgets to JSON
     * @param formWidget Form widget containing form fields
     * @return JSON string of form data
     */
    QString serializeFormData(QWidget* formWidget);
    
    /**
     * @brief Load form data from JSON to widgets
     * @param formWidget Form widget containing form fields
     * @param jsonData JSON string of form data
     * @return true if successful, false otherwise
     */
    bool loadFormData(QWidget* formWidget, const QString& jsonData);
    
    /**
     * @brief Get last error message
     * @return Error message string, empty if no error
     */
    QString lastError() const { return m_lastError; }

private:
    QString m_lastError;
    
    /**
     * @brief Extract value from a widget
     * @param widget Widget to extract value from
     * @return JSON value
     */
    QJsonValue extractWidgetValue(QWidget* widget);
    
    /**
     * @brief Set value on a widget
     * @param widget Widget to set value on
     * @param value JSON value to set
     * @return true if successful, false otherwise
     */
    bool setWidgetValue(QWidget* widget, const QJsonValue& value);
};

} // namespace forms
} // namespace common
} // namespace smartbook

#endif // SMARTBOOK_COMMON_FORMS_FORMDATASERIALIZER_H

